Repository koikiss-dev/jimov_api, pull requests merged in 2024-06, with the labels that each got.

#162 feat(provider)!: add provider abstract classes and interfaces
  src/models/AnimeScraperModel.ts
  src/models/BaseScraperModel.ts
  src/models/MangaScraperModel.ts
  src/routes/v1/anime/animeblix/AnimeBlixRoutes.ts
  src/routes/v1/anime/animeflv/AnimeflvRoutes.ts
  src/routes/v1/anime/animelatinohd/AnimeLatinoHDRoutes.ts
  src/routes/v1/anime/animevostfr/AnimevostfrRoutes.ts
  src/routes/v1/anime/wcostream/wcostreamRoutes.ts
  src/routes/v1/anime/zoro/ZoroRoutes.ts
  src/scraper/ScraperAnimeModel.ts
  src/scraper/sites/anime/animeBlixs/AnimeBlix.ts
  src/scraper/sites/anime/animeflv/AnimeFlv.ts
  src/scraper/sites/anime/animelatinohd/AnimeLatinoHD.ts
  src/scraper/sites/anime/animevostfr/Animevostfr.ts
  src/scraper/sites/anime/wcostream/WcoStream.ts
  src/scraper/sites/anime/zoro/Zoro.ts
  src/scraper/sites/manga/mangaStructure.ts
  src/test/Animeflv.spec.ts
  src/test/Animelatinohd.spec.ts
  src/test/Zoro.spec.ts
  src/types/anime.ts
  src/types/base.ts
  src/types/episode.ts
  src/types/manga.ts
  src/types/search.ts
Labels: fix, breaking change

#167 fix(providers): migrating the class implementation of MangaReader and Manganelo
  src/routes/v1/manga/manganelo/ManganeloRoutes.ts
  src/routes/v1/manga/mangareader/MangaReaderRoutes.ts
  src/scraper/sites/manga/MangaReader/MangaReader.ts
  src/scraper/sites/manga/manganelo/Manganelo.ts
  src/test/MangaReader.spec.ts
  src/test/Manganelo.spec.ts
Labels: fix

#164 Fix: classes in multiple provides, fixed usage: AnimeLatinoHD || Add package(crypto-js)
  bun.lockb
  package-lock.json
  package.json
  src/routes/v1/anime/animevostfr/AnimevostfrRoutes.ts
  src/routes/v1/manga/comick/ComickRoutes.ts
  src/scraper/sites/anime/animeBlixs/AnimeBlix.ts
  src/scraper/sites/anime/animelatinohd/AnimeLatinoHD.ts
  src/scraper/sites/anime/animevostfr/Animevostfr.ts
  src/scraper/sites/anime/wcostream/WcoStream.ts
  src/scraper/sites/manga/comick/Comick.ts
  src/scraper/sites/manga/inmanga/Inmanga.ts
  src/test/Animelatinohd.spec.ts
  src/test/Comick.spec.ts
  src/test/Inmanga.spec.ts
Labels: fix, Upgrade provider
